// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectS() *S {
	a := newA()
	s := &S{
		foo: a,
	}
	return s
}

// foo.go:

type A struct{ N int }

type S struct {
	Foo A
	foo A
}

func newA() A {
	return A{N: 1}
}

func main() {
	fmt.Println(injectS().foo.N)
}
