// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectI2() I2 {
	c := newC()
	return c
}

// foo.go:

type I1 interface {
	M() int
}

type I2 interface {
	M() int
}

type C struct{}

func (C) M() int { return 5 }

func newC() *C {
	return &C{}
}

func main() {
	fmt.Println(injectI2().M())
}
