// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"unsafe"
)

// Injectors from wire.go:

func inject() (unsafe.Pointer, error) {
	pointer, err := provide()
	if err != nil {
		return nil, err
	}
	return pointer, nil
}
