// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectS() S {
	int2 := provideInt()
	s := S{
		N: int2,
	}
	return s
}

// foo.go:

type S struct {
	N int
}

func provideInt() int {
	return 7
}

func main() {
	fmt.Println(injectS().N)
}
