// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	other2 "example.com/other"
)

// Injectors from wire.go:

func injectFirst() other2.Box[int] {
	box := other2.Make[int]()
	return box
}

func injectAny[T any]() (T, error) {
	v, err := fail[T]()
	if err != nil {
		var zero T
		return zero, err
	}
	return v, nil
}

func injectInt[T ~int]() (T, error) {
	v, err := fail[T]()
	if err != nil {
		var zero T
		return zero, err
	}
	return v, nil
}

func injectStruct[T ~struct{ N int }]() (T, error) {
	v, err := fail[T]()
	if err != nil {
		var zero T
		return zero, err
	}
	return v, nil
}

func injectErr[err any]() (*err, error) {
	v, err2 := failPtr[err]()
	if err2 != nil {
		var zero *err
		return zero, err2
	}
	return v, nil
}

func injectZero[zero any]() (zero, error) {
	v, err := fail[zero]()
	if err != nil {
		var zero2 zero
		return zero2, err
	}
	return v, nil
}

func injectNew[T any]() (T, error) {
	v, err := fail[T]()
	if err != nil {
		var zero T
		return zero, err
	}
	return v, nil
}

func injectCleanup[cleanup any]() (*cleanup, func()) {
	v, cleanup2 := resource[cleanup]()
	return v, func() {
		cleanup2()
	}
}

func injectV[v any]() *v {
	v2 := value[v]()
	return v2
}

func injectUnused[T any]() int {
	int2 := _wireIntValue
	return int2
}

var (
	_wireIntValue = 7
)

func injectConstraint[T other2.Number](v T) T {
	return v
}

func injectImport[other any]() other2.Box[other] {
	box := other2.Make[other]()
	return box
}
