// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectInt() int {
	int2 := provideInt()
	return int2
}

// foo.go:

// x collides with the package-level x in the generated file's scope.
var x = 0

func helper() int {
	x2 := 1
	x3 := 2
	_ = x3
	return x2
}

func provideInt() int {
	return helper()
}

func main() {
	fmt.Println(injectInt(), x)
}
