// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

func injectBox() Box[int] {
	int2 := provideInt()
	box := MakeBox[int](int2)
	return box
}

// foo.go:

type Box[T any] struct {
	V T
}

type Pair[A, B any] struct {
	A A
	B B
}

// defaultPair and Identity are non-injector declarations that exercise
// generic type parameters and multi-argument instantiations when copied.
var defaultPair = Pair[int, string]{A: 1, B: "two"}

func Identity[T any](v T) T {
	return v
}

func MakeBox[T any](v T) Box[T] {
	return Box[T]{V: v}
}

func provideInt() int {
	return 42
}

func main() {
	box := injectBox()
	fmt.Println(box.V, defaultPair.A, defaultPair.B, Identity(7))
}
