// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectBox() Box[int] {
	box := _wireBoxValue
	return box
}

var (
	_wireBoxValue = Box[int]{V: 7}
)

func injectPair() Pair[int, string] {
	pair := _wirePairValue
	return pair
}

var (
	_wirePairValue = Pair[int, string]{A: 7, B: "ok"}
)
