// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
)

// Injectors from foo.go:

// Return underlying types to keep the golden independent of go/types alias
// representation. The Struct markers must still resolve the aliases.
func injectAlias() S {
	int2 := provideInt()
	s := SAlias{
		N: int2,
	}
	return s
}

func injectIntBox() Box[int] {
	int2 := provideInt()
	box := IntBox{
		V: int2,
	}
	return box
}

func injectAnonymous() struct{ N int } {
	int2 := provideInt()
	v := Anonymous{
		N: int2,
	}
	return v
}

// foo.go:

type S struct {
	N int
}

// SAlias and IntBox are type aliases; wire.Struct must accept them.
type SAlias = S

type Box[T any] struct {
	V T
}

type IntBox = Box[int]

type Anonymous = struct{ N int }

func provideInt() int {
	return 7
}

func main() {
	fmt.Println(injectAlias().N, injectIntBox().V, injectAnonymous().N)
}
