// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func injectBox() *Box[int] {
	int2 := _wireIntValue
	box := &Box[int]{
		V: int2,
	}
	return box
}

var (
	_wireIntValue = 7
)

func injectAlias() Box[int] {
	int2 := _wireIntValue2
	box := IntBox{
		V: int2,
	}
	return box
}

var (
	_wireIntValue2 = 7
)

func injectPair() Pair[int, string] {
	int2 := _wireIntValue3
	string2 := _wireStringValue
	pair := Pair[int, string]{
		A: int2,
		B: string2,
	}
	return pair
}

var (
	_wireIntValue3   = 7
	_wireStringValue = "ok"
)
