// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/wireinject/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func inject(fail bool) (int, error) {
	int2, err2 := provide(fail)
	if err2 != nil {
		return 0, err2
	}
	return int2, nil
}
